modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="${mod_issues}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description="${mod_description}"
logoFile= "assets/pangaea/icon.png"

[[dependencies.${mod_id}]]
modId="catlib"
mandatory=true
versionRange="[${catlib_min_version},)"
ordering="AFTER"
side="BOTH"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[mixins]]
config="pangaea.common.mixins.json"